#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_45244_shwe8")]
public partial class NewsDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertnews_post(news_post instance);
  partial void Updatenews_post(news_post instance);
  partial void Deletenews_post(news_post instance);
  partial void Insertnews_source(news_source instance);
  partial void Updatenews_source(news_source instance);
  partial void Deletenews_source(news_source instance);
  partial void Insertnews_type(news_type instance);
  partial void Updatenews_type(news_type instance);
  partial void Deletenews_type(news_type instance);
  #endregion
	
	public NewsDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CAKE_WAVEConnectionString4"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public NewsDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public NewsDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public NewsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public NewsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<news_post> news_posts
	{
		get
		{
			return this.GetTable<news_post>();
		}
	}
	
	public System.Data.Linq.Table<news_source> news_sources
	{
		get
		{
			return this.GetTable<news_source>();
		}
	}
	
	public System.Data.Linq.Table<news_type> news_types
	{
		get
		{
			return this.GetTable<news_type>();
		}
	}
	
	public System.Data.Linq.Table<filtered_news_post> filtered_news_posts
	{
		get
		{
			return this.GetTable<filtered_news_post>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.news_post")]
public partial class news_post : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _news_id;
	
	private string _subject;
	
	private string _body;
	
	private string _news_type_id;
	
	private System.DateTime _post_on;
	
	private string _news_source_id;
	
	private string _img_url;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnews_idChanging(string value);
    partial void Onnews_idChanged();
    partial void OnsubjectChanging(string value);
    partial void OnsubjectChanged();
    partial void OnbodyChanging(string value);
    partial void OnbodyChanged();
    partial void Onnews_type_idChanging(string value);
    partial void Onnews_type_idChanged();
    partial void Onpost_onChanging(System.DateTime value);
    partial void Onpost_onChanged();
    partial void Onnews_source_idChanging(string value);
    partial void Onnews_source_idChanged();
    partial void Onimg_urlChanging(string value);
    partial void Onimg_urlChanged();
    #endregion
	
	public news_post()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_id", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string news_id
	{
		get
		{
			return this._news_id;
		}
		set
		{
			if ((this._news_id != value))
			{
				this.Onnews_idChanging(value);
				this.SendPropertyChanging();
				this._news_id = value;
				this.SendPropertyChanged("news_id");
				this.Onnews_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string subject
	{
		get
		{
			return this._subject;
		}
		set
		{
			if ((this._subject != value))
			{
				this.OnsubjectChanging(value);
				this.SendPropertyChanging();
				this._subject = value;
				this.SendPropertyChanged("subject");
				this.OnsubjectChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_body", DbType="NVarChar(4000) NOT NULL", CanBeNull=false)]
	public string body
	{
		get
		{
			return this._body;
		}
		set
		{
			if ((this._body != value))
			{
				this.OnbodyChanging(value);
				this.SendPropertyChanging();
				this._body = value;
				this.SendPropertyChanged("body");
				this.OnbodyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_type_id", DbType="VarChar(20)")]
	public string news_type_id
	{
		get
		{
			return this._news_type_id;
		}
		set
		{
			if ((this._news_type_id != value))
			{
				this.Onnews_type_idChanging(value);
				this.SendPropertyChanging();
				this._news_type_id = value;
				this.SendPropertyChanged("news_type_id");
				this.Onnews_type_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_on", DbType="DateTime NOT NULL")]
	public System.DateTime post_on
	{
		get
		{
			return this._post_on;
		}
		set
		{
			if ((this._post_on != value))
			{
				this.Onpost_onChanging(value);
				this.SendPropertyChanging();
				this._post_on = value;
				this.SendPropertyChanged("post_on");
				this.Onpost_onChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_source_id", DbType="VarChar(50)")]
	public string news_source_id
	{
		get
		{
			return this._news_source_id;
		}
		set
		{
			if ((this._news_source_id != value))
			{
				this.Onnews_source_idChanging(value);
				this.SendPropertyChanging();
				this._news_source_id = value;
				this.SendPropertyChanged("news_source_id");
				this.Onnews_source_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_url", DbType="VarChar(500)")]
	public string img_url
	{
		get
		{
			return this._img_url;
		}
		set
		{
			if ((this._img_url != value))
			{
				this.Onimg_urlChanging(value);
				this.SendPropertyChanging();
				this._img_url = value;
				this.SendPropertyChanged("img_url");
				this.Onimg_urlChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.news_source")]
public partial class news_source : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _news_source_id;
	
	private string _source_name;
	
	private int _enable;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnews_source_idChanging(string value);
    partial void Onnews_source_idChanged();
    partial void Onsource_nameChanging(string value);
    partial void Onsource_nameChanged();
    partial void OnenableChanging(int value);
    partial void OnenableChanged();
    #endregion
	
	public news_source()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_source_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string news_source_id
	{
		get
		{
			return this._news_source_id;
		}
		set
		{
			if ((this._news_source_id != value))
			{
				this.Onnews_source_idChanging(value);
				this.SendPropertyChanging();
				this._news_source_id = value;
				this.SendPropertyChanged("news_source_id");
				this.Onnews_source_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string source_name
	{
		get
		{
			return this._source_name;
		}
		set
		{
			if ((this._source_name != value))
			{
				this.Onsource_nameChanging(value);
				this.SendPropertyChanging();
				this._source_name = value;
				this.SendPropertyChanged("source_name");
				this.Onsource_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enable", DbType="Int NOT NULL")]
	public int enable
	{
		get
		{
			return this._enable;
		}
		set
		{
			if ((this._enable != value))
			{
				this.OnenableChanging(value);
				this.SendPropertyChanging();
				this._enable = value;
				this.SendPropertyChanged("enable");
				this.OnenableChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.news_type")]
public partial class news_type : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _news_type_id;
	
	private string _news_type_description;
	
	private int _enable;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnews_type_idChanging(string value);
    partial void Onnews_type_idChanged();
    partial void Onnews_type_descriptionChanging(string value);
    partial void Onnews_type_descriptionChanged();
    partial void OnenableChanging(int value);
    partial void OnenableChanged();
    #endregion
	
	public news_type()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_type_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string news_type_id
	{
		get
		{
			return this._news_type_id;
		}
		set
		{
			if ((this._news_type_id != value))
			{
				this.Onnews_type_idChanging(value);
				this.SendPropertyChanging();
				this._news_type_id = value;
				this.SendPropertyChanged("news_type_id");
				this.Onnews_type_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_type_description", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string news_type_description
	{
		get
		{
			return this._news_type_description;
		}
		set
		{
			if ((this._news_type_description != value))
			{
				this.Onnews_type_descriptionChanging(value);
				this.SendPropertyChanging();
				this._news_type_description = value;
				this.SendPropertyChanged("news_type_description");
				this.Onnews_type_descriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enable", DbType="Int NOT NULL")]
	public int enable
	{
		get
		{
			return this._enable;
		}
		set
		{
			if ((this._enable != value))
			{
				this.OnenableChanging(value);
				this.SendPropertyChanging();
				this._enable = value;
				this.SendPropertyChanged("enable");
				this.OnenableChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.filtered_news_post")]
public partial class filtered_news_post
{
	
	private string _news_id;
	
	private string _subject;
	
	private string _body;
	
	private string _news_type_id;
	
	private System.DateTime _post_on;
	
	private string _news_source_id;
	
	private string _img_url;
	
	private string _source_name;
	
	private string _news_type_description;
	
	public filtered_news_post()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_id", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string news_id
	{
		get
		{
			return this._news_id;
		}
		set
		{
			if ((this._news_id != value))
			{
				this._news_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string subject
	{
		get
		{
			return this._subject;
		}
		set
		{
			if ((this._subject != value))
			{
				this._subject = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_body", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string body
	{
		get
		{
			return this._body;
		}
		set
		{
			if ((this._body != value))
			{
				this._body = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_type_id", DbType="VarChar(20)")]
	public string news_type_id
	{
		get
		{
			return this._news_type_id;
		}
		set
		{
			if ((this._news_type_id != value))
			{
				this._news_type_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_on", DbType="DateTime NOT NULL")]
	public System.DateTime post_on
	{
		get
		{
			return this._post_on;
		}
		set
		{
			if ((this._post_on != value))
			{
				this._post_on = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_source_id", DbType="VarChar(50)")]
	public string news_source_id
	{
		get
		{
			return this._news_source_id;
		}
		set
		{
			if ((this._news_source_id != value))
			{
				this._news_source_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_url", DbType="VarChar(500)")]
	public string img_url
	{
		get
		{
			return this._img_url;
		}
		set
		{
			if ((this._img_url != value))
			{
				this._img_url = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string source_name
	{
		get
		{
			return this._source_name;
		}
		set
		{
			if ((this._source_name != value))
			{
				this._source_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_news_type_description", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string news_type_description
	{
		get
		{
			return this._news_type_description;
		}
		set
		{
			if ((this._news_type_description != value))
			{
				this._news_type_description = value;
			}
		}
	}
}
#pragma warning restore 1591
