<?xml version="1.0" encoding="utf-8"?><Database Name="CAKE_WAVE" Class="QuoteDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=CAKE_WAVE;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="cake_waveConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.quote_post" Member="quote_posts">
    <Type Name="quote_post">
      <Column Name="quote_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="quote_typeid" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="quote_by" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="post_on" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="contact_no" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.quote_type" Member="quote_types">
    <Type Name="quote_type">
      <Column Name="quote_typeid" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="quote_typename" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.filtered_quote_post" Member="filtered_quote_posts">
    <Type Name="filtered_quote_post">
      <Column Name="quote_id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="quote_typeid" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="quote_by" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="post_on" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="contact_no" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="quote_typename" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>