#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CAKE_WAVE")]
public partial class QuoteDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertquote_post(quote_post instance);
  partial void Updatequote_post(quote_post instance);
  partial void Deletequote_post(quote_post instance);
  partial void Insertquote_type(quote_type instance);
  partial void Updatequote_type(quote_type instance);
  partial void Deletequote_type(quote_type instance);
  #endregion
	
	public QuoteDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["cake_waveConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public QuoteDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QuoteDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QuoteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public QuoteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<quote_post> quote_posts
	{
		get
		{
			return this.GetTable<quote_post>();
		}
	}
	
	public System.Data.Linq.Table<quote_type> quote_types
	{
		get
		{
			return this.GetTable<quote_type>();
		}
	}
	
	public System.Data.Linq.Table<filtered_quote_post> filtered_quote_posts
	{
		get
		{
			return this.GetTable<filtered_quote_post>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.quote_post")]
public partial class quote_post : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _quote_id;
	
	private string _description;
	
	private string _quote_typeid;
	
	private string _quote_by;
	
	private System.DateTime _post_on;
	
	private string _email;
	
	private string _contact_no;
	
	private string _title;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onquote_idChanging(string value);
    partial void Onquote_idChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onquote_typeidChanging(string value);
    partial void Onquote_typeidChanged();
    partial void Onquote_byChanging(string value);
    partial void Onquote_byChanged();
    partial void Onpost_onChanging(System.DateTime value);
    partial void Onpost_onChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Oncontact_noChanging(string value);
    partial void Oncontact_noChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    #endregion
	
	public quote_post()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quote_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string quote_id
	{
		get
		{
			return this._quote_id;
		}
		set
		{
			if ((this._quote_id != value))
			{
				this.Onquote_idChanging(value);
				this.SendPropertyChanging();
				this._quote_id = value;
				this.SendPropertyChanged("quote_id");
				this.Onquote_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(4000) NOT NULL", CanBeNull=false)]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quote_typeid", DbType="VarChar(10)")]
	public string quote_typeid
	{
		get
		{
			return this._quote_typeid;
		}
		set
		{
			if ((this._quote_typeid != value))
			{
				this.Onquote_typeidChanging(value);
				this.SendPropertyChanging();
				this._quote_typeid = value;
				this.SendPropertyChanged("quote_typeid");
				this.Onquote_typeidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quote_by", DbType="NVarChar(200)")]
	public string quote_by
	{
		get
		{
			return this._quote_by;
		}
		set
		{
			if ((this._quote_by != value))
			{
				this.Onquote_byChanging(value);
				this.SendPropertyChanging();
				this._quote_by = value;
				this.SendPropertyChanged("quote_by");
				this.Onquote_byChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_on", DbType="DateTime NOT NULL")]
	public System.DateTime post_on
	{
		get
		{
			return this._post_on;
		}
		set
		{
			if ((this._post_on != value))
			{
				this.Onpost_onChanging(value);
				this.SendPropertyChanging();
				this._post_on = value;
				this.SendPropertyChanged("post_on");
				this.Onpost_onChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_no", DbType="VarChar(20)")]
	public string contact_no
	{
		get
		{
			return this._contact_no;
		}
		set
		{
			if ((this._contact_no != value))
			{
				this.Oncontact_noChanging(value);
				this.SendPropertyChanging();
				this._contact_no = value;
				this.SendPropertyChanged("contact_no");
				this.Oncontact_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(200)")]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.quote_type")]
public partial class quote_type : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _quote_typeid;
	
	private string _quote_typename;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onquote_typeidChanging(string value);
    partial void Onquote_typeidChanged();
    partial void Onquote_typenameChanging(string value);
    partial void Onquote_typenameChanged();
    #endregion
	
	public quote_type()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quote_typeid", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string quote_typeid
	{
		get
		{
			return this._quote_typeid;
		}
		set
		{
			if ((this._quote_typeid != value))
			{
				this.Onquote_typeidChanging(value);
				this.SendPropertyChanging();
				this._quote_typeid = value;
				this.SendPropertyChanged("quote_typeid");
				this.Onquote_typeidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quote_typename", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string quote_typename
	{
		get
		{
			return this._quote_typename;
		}
		set
		{
			if ((this._quote_typename != value))
			{
				this.Onquote_typenameChanging(value);
				this.SendPropertyChanging();
				this._quote_typename = value;
				this.SendPropertyChanged("quote_typename");
				this.Onquote_typenameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.filtered_quote_post")]
public partial class filtered_quote_post
{
	
	private string _quote_id;
	
	private string _description;
	
	private string _quote_typeid;
	
	private string _quote_by;
	
	private System.DateTime _post_on;
	
	private string _email;
	
	private string _contact_no;
	
	private string _quote_typename;
	
	private string _title;
	
	public filtered_quote_post()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quote_id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string quote_id
	{
		get
		{
			return this._quote_id;
		}
		set
		{
			if ((this._quote_id != value))
			{
				this._quote_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(4000) NOT NULL", CanBeNull=false)]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this._description = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quote_typeid", DbType="VarChar(10)")]
	public string quote_typeid
	{
		get
		{
			return this._quote_typeid;
		}
		set
		{
			if ((this._quote_typeid != value))
			{
				this._quote_typeid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quote_by", DbType="NVarChar(200)")]
	public string quote_by
	{
		get
		{
			return this._quote_by;
		}
		set
		{
			if ((this._quote_by != value))
			{
				this._quote_by = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_post_on", DbType="DateTime NOT NULL")]
	public System.DateTime post_on
	{
		get
		{
			return this._post_on;
		}
		set
		{
			if ((this._post_on != value))
			{
				this._post_on = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this._email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_no", DbType="VarChar(20)")]
	public string contact_no
	{
		get
		{
			return this._contact_no;
		}
		set
		{
			if ((this._contact_no != value))
			{
				this._contact_no = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quote_typename", DbType="NVarChar(200)")]
	public string quote_typename
	{
		get
		{
			return this._quote_typename;
		}
		set
		{
			if ((this._quote_typename != value))
			{
				this._quote_typename = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(200)")]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this._title = value;
			}
		}
	}
}
#pragma warning restore 1591
