<?xml version="1.0" encoding="utf-8"?><Database Name="cake_wave" Class="RoomsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\cake_wave.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="cake_waveConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.room" Member="rooms">
    <Type Name="room">
      <Column Name="room_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="available_type" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="postal_code" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="contact_no" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="available" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="aircon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="remarks" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="post_on" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="view_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>